spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  jpa:
    show-sql: false

logging:
  level:
    br.com.holding.payments: INFO
    org.hibernate.SQL: WARN

app:
  asaas:
    base-url: https://sandbox.asaas.com/api/v3
