name: CI/CD Payment API - Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build & Deploy Payment API
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build Maven
        run: |
          set -e
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Deploy e Reinício do Serviço
        run: |
          set -e
          echo "--- Preparando a pasta de produção..."
          sudo mkdir -p /opt/pay
          sudo rm -f /opt/pay/docker-compose.yml /opt/pay/Dockerfile /opt/pay/*.jar

          sudo cp docker-compose.yml /opt/pay/
          sudo cp Dockerfile /opt/pay/
          sudo cp target/payment-api-*.jar /opt/pay/app.jar

          cd /opt/pay
          sudo docker system prune -f
          sudo docker compose down
          sudo docker compose up -d --build

          echo "--- Deploy concluído com sucesso!"